package printer

import "strings"

func String(packageName, typeName, fields string) string {
	result := strings.ReplaceAll(template, "$(package)", packageName)
	result = strings.ReplaceAll(result, "$(type)", typeName)
	result = strings.ReplaceAll(result, "$(fields)", fields)
	return result
}

var template = `// Code generated by structstringer
// DO NOT EDIT!
package $(package)

import "strings"
import "strconv"

func (t $(type)) String() string {
	var builder strings.Builder
	builder.Grow(80) // TODO count
	builder.WriteString("\n$(type){")$(fields)
	builder.WriteString("\n}")
	return builder.String()
}
`
