// Code generated by structstringer
// DO NOT EDIT!
package recursive

import (
	"strconv"
	"strings"
)

func (t D) String() string {
	var builder strings.Builder
	builder.Grow(1024) // TODO count
	builder.WriteString("\nrecursive.D{")
	builder.WriteString("\n\ti    int      ")
	builder.WriteString(strconv.Itoa(t.i))
	builder.WriteString("\n\tflag bool     ")
	builder.WriteString(strconv.FormatBool(t.flag))
	builder.WriteString("\n\tb    simple.B ")
	builder.WriteRune('{')
	builder.WriteString("\n\t\tI int ")
	builder.WriteString(strconv.Itoa(t.b.I))
	builder.WriteString("\n\t}")
	builder.WriteString("\n}")
	return builder.String()
}
