// Code generated by structstringer
// DO NOT EDIT!
package recursive

import (
	"strconv"
	"strings"
)

func (t E) String() string {
	var builder strings.Builder
	builder.Grow(1024) // TODO count
	builder.WriteString("\nrecursive.E{")
	builder.WriteString("\n\ti    int      ")
	builder.WriteString(strconv.Itoa(t.i))
	builder.WriteString("\n\tflag bool     ")
	builder.WriteString(strconv.FormatBool(t.flag))
	builder.WriteString("\n\tc    simple.C ")
	builder.WriteRune('{')
	builder.WriteString("\n\t\tI    int  ")
	builder.WriteString(strconv.Itoa(t.c.I))
	builder.WriteString("\n\t\tflag bool ")
	builder.WriteString("not_implemented_unexported_fields")
	builder.WriteString("\n\t}")
	builder.WriteString("\n}")
	return builder.String()
}
